config/routes.rb
# Page titles on Wikipedia may include dots, so this constraint is needed.

Rails.application.routes.draw do
  get 'errors/file_not_found'
  get 'errors/unprocessable'
  get 'errors/login_error'
  get 'errors/internal_server_error'
  get 'errors/incorrect_passcode'

  # Sessions
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    # OmniAuth may fall back to :new_user_session when the OAuth flow fails.
    # So, we treat it as a login error.
    get 'sign_in', to: 'errors#login_error', as: :new_user_session

    get 'sign_out', to: 'users#signout', as: :destroy_user_session
    get 'sign_out_oauth', to: 'devise/sessions#destroy',
                          as: :true_destroy_user_session
  end

  # Users
  controller :users do
    get 'users/revisions' => 'users#revisions', :as => :user_revisions
  end

  resources :assignments

  # Self-enrollment: joining a course by entering a passcode or visiting a url
  get 'courses/:course_id/enroll/:passcode' => 'self_enrollment#enroll_self',
      constraints: { course_id: /.*/ }

  # Courses
  controller :courses do
    get 'courses/*id/get_wiki_top_section' => 'courses#get_wiki_top_section',
        :as => :get_wiki_top_section, constraints: { id: /.*/ }
    get 'courses/new' => 'courses#new',
        constraints: { id: /.*/ } # repeat of resources

    get 'courses/*id/manual_update' => 'courses#manual_update',
        :as => :manual_update, constraints: { id: /.*/ }
    get 'courses/*id/notify_untrained' => 'courses#notify_untrained',
        :as => :notify_untrained, constraints: { id: /.*/ }

    get 'courses/*id/check' => 'courses#check',
        :as => :check, constraints: { id: /.*/ }
    match 'courses/*id/cohort' => 'courses#list',
          constraints: { id: /.*/ }, via: [:post, :delete]
    match 'courses/*id/tag' => 'courses#tag',
          constraints: { id: /.*/ }, via: [:post, :delete]
    match 'courses/*id/user' => 'users#enroll',
          constraints: { id: /.*/ }, via: [:post, :delete]

    get 'courses/:school/:titleterm(/:endpoint(/*any))' => 'courses#show',
        defaults: { endpoint: 'overview' }, :as => 'show',
        constraints: {
          school: /[^\/]*/,
          titleterm: /[^\/]*/
        }
    post 'clone_course/:id' => 'courses#clone'
    post 'courses/:id/update_syllabus' => 'courses#update_syllabus'
  end

  get 'lookups/(:action)(.:format)' => 'lookups'

  # Assigning articles to students
  post 'courses/:course_id/users' => 'users#save_assignments',
       constraints: { course_id: /.*/ }

  # Timeline
  resources :courses, constraints: { id: /.*/ } do
    resources :weeks, only: [:index, :new, :create], constraints: { id: /.*/ }
    # get 'courses' => 'courses#index'
  end
  resources :weeks, only: [:index, :show, :edit, :update, :destroy]
  resources :blocks, only: [:show, :edit, :update, :destroy]
  resources :gradeables, collection: { update_multiple: :put }
  post 'courses/:course_id/timeline' => 'timeline#update_timeline',
       constraints: { course_id: /.*/ }

  get 'revisions' => 'revisions#index'

  resources :courses_users, only: [:index]

  # Article Finder
  if Features.enable_article_finder?
    get 'article_finder(/*any)' => 'article_finder#index'
    post 'article_finder(/*any)' => 'article_finder#results'
  end

  # Reports and analytics
  get 'analytics(/*any)' => 'analytics#index'
  post 'analytics(/*any)' => 'analytics#results'

  # Cohort data
  controller :cohorts do
    get 'cohorts/:slug/students' => 'cohorts#students'
  end

  # Recent Activity
  get 'recent-activity/plagiarism/report' => 'recent_activity#plagiarism_report'
  get 'recent-activity(/*any)' => 'recent_activity#index', as: :recent_activity

  # Revision analytics JSON API for React
  get 'revision_analytics/dyk_eligible',
      controller: 'revision_analytics',
      action: 'dyk_eligible'
  get 'revision_analytics/suspected_plagiarism',
      controller: 'revision_analytics',
      action: 'suspected_plagiarism'
  get 'revision_analytics/recent_edits',
      controller: 'revision_analytics',
      action: 'recent_edits'
  get 'revision_analytics/recent_uploads',
      controller: 'revision_analytics',
      action: 'recent_uploads'



  # Wizard
  get 'wizards' => 'wizard#wizard_index'
  get 'wizards/:wizard_id' => 'wizard#wizard'
  post 'courses/:course_id/wizard/:wizard_id' => 'wizard#submit_wizard',
       constraints: { course_id: /.*/ }

  # Training
  get 'training' => 'training#index'
  get 'training/:library_id' => 'training#show', as: :training_library
  get 'training/:library_id/:module_id' => 'training#training_module', as: :training_module
  post 'training_modules_users' => 'training_modules_users#create_or_update'

  # for React
  get 'training/:library_id/:module_id(/*any)' => 'training#slide_view'

  # API for slides for a module
  get 'training_modules' => 'training_modules#index'
  get 'training_module' => 'training_modules#show'


  # Misc
  # get 'courses' => 'courses#index'
  get 'explore' => 'explore#index'
  # get 'courses/*id' => 'courses#show', :as => :show, constraints: { id: /.*/ }

  # ask.wikiedu.org search box
  get 'ask' => 'ask#search'

  # Authenticated users root to the courses dashboard
  authenticated :user do
    root to: "dashboard#index", as: :courses_dashboard
  end

  # Unauthenticated users root to the home page
  root to: 'home#index'

  mount Rapidfire::Engine => "/surveys/rapidfire", :as => 'rapidfire'
  get '/surveys/results' => 'surveys#results_index', as: 'results'
  resources :survey_assignments, path: 'surveys/assignments'
  post '/surveys/clone/:id' => 'surveys#clone'
  put '/surveys/question_position' => 'questions#update_position'
  get '/survey/results/:id' => 'surveys#results', as: 'survey_results'
  get '/survey/question/results/:id' => 'questions#results', as: 'question_results'
  get '/surveys/question_group_question/:id' => 'questions#get_question'
  get '/surveys/:id/question_group' => 'surveys#edit_question_groups', :as => "edit_question_groups"
  post '/surveys/question_group/clone/:id' => 'surveys#clone_question_group'
  post '/surveys/question/clone/:id' => 'surveys#clone_question'
  post '/surveys/update_question_group_position' => 'surveys#update_question_group_position'
  resources :surveys
  get '/surveys/select_course/:id' => 'surveys#course_select'
  put '/survey_notification' => 'survey_notifications#update'
  post '/survey_notification/create' => 'survey_assignments#create_notifications', as: 'create_notifications'
  post '/survey_notification/send' => 'survey_assignments#send_notifications', as: 'send_notifications'

  # Onboarding
  get 'onboarding(/*any)' => 'onboarding#index', as: :onboarding
  put 'users/onboard' => 'users#onboard', as: :onboard

  # Route aliases for React frontend
  get '/course_creator(/*any)' => 'dashboard#index', as: :course_creator

  get '/feedback' => 'feedback_form_responses#new', as: :feedback
  get '/feedback_form_responses' => 'feedback_form_responses#index'
  get '/feedback_form_responses/:id' => 'feedback_form_responses#show', as: :feedback_form_response
  post '/feedback_form_responses' => 'feedback_form_responses#create'
  get '/feedback/confirmation' => 'feedback_form_responses#confirmation'

  # Errors
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/599', to: 'errors#login_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/dashboard_controller.rb
#= Controller for dashboard functionality
class DashboardController < ApplicationController
  respond_to :html

  def index
    unless current_user
      redirect_to root_path
      return
    end

    set_admin_courses_if_admin

    @pres = DashboardPresenter.new(current_courses, past_courses,
                                   @submitted, @strictly_current, current_user)
  end

  private

  def set_admin_courses_if_admin
    @submitted = []
    @strictly_current = []

    return unless current_user.admin?
    @submitted = Course.submitted_listed
    @strictly_current = current_user.courses.strictly_current
  end

  def current_courses
    current_user.courses.current_and_future.listed
  end

  def past_courses
    # Admins see course lists based strictly on start and end dates.
    # Other users have course lists based on the 'current' scope, which
    # include courses that have just ended.
    # This makes sure the combination of displayed courses includes all courses,
    # without leaving some stuck in between being past and current.
    if current_user.admin?
      current_user.courses.where('end <= ?', Date.today)
    else
      current_user.courses.archived.listed
    end
  end
end

app/views/dashboard/_course_row.html.haml
= link_to course_slug_path(course.slug), class: 'course' do
  %span.button.border
    = t("courses.view_page")
  .course-title
    = course.title
  .course-details
    .col
      .course-details_title
        = t("courses.instructors")
      .course-details_value
        - course.instructors.each do |user|
          = user.username
    .col
      .course-details_title
        = t("courses.school")
      .course-details_value
        = course.school
    .col
      .course-details_title
        = t("courses.term")
      .course-details_value
        = course.term
    .col
      .course-details_title
        = t("courses.students_count")
      .course-details_value
        = course.students.length

app/views/dashboard/index.html.haml
- content_for :after_title, " - " + t("application.my_dashboard")

#react_root{data: {default_course_type: @pres.default_course_type,
                   course_string_prefix: @pres.default_course_string_prefix}}
.container.dashboard
  %header
    %h1= @pres.heading_message
    %div

      - if @pres.can_create_course?
        = link_to course_creator_path, class: 'button dark dashboard-cta' do
          = t("courses.creator.create_short")
          %i.icon.icon-plus
        - if Features.open_course_creation?
          %div
            = link_to explore_path, class: 'button stacked dark dashboard-cta' do
              = t("courses.creator.find_program")
              %span.icon.icon-rt_arrow
      - elsif @pres.show_explore_button?
        = link_to explore_path, class: 'button dark dashboard-cta' do
          = t("courses.creator.find")
          %span.icon.icon-rt_arrow

    - if @pres.show_orientation_review?
      %div
        = link_to @pres.orientation_path, class: 'button' do
          = t("dashboard.review_orientation")
          %i.icon.icon-rt_arrow
  - # Show submitted/pending courses (for admins)
  - if @pres.submitted.any?
    %h2
      = t("courses.submitted_and_pending_heading")
    - @pres.submitted.each do |course|
      = render "course_row", course: course

  - # Orientation block
  - if @pres.show_orientation_block?
    %div.empty-state
      %p
        = t("dashboard.orientation_notice")
      %p
        = link_to @pres.orientation_path, class: 'button dark' do
          = t("dashboard.start_orientation")
          %i.icon.icon-rt_arrow
      %p.small
        = link_to t('dashboard.opt_out'), @pres.opt_out_path

  - if @pres.show_your_courses_label?
    %h2
      = t("courses.yourcourses")

  - # Empty courses state
  - if @pres.current.empty? && @pres.past.empty?
    - if @pres.can_create_course?
      %div.empty-state
        %p
          = t("dashboard.no_courses_instructor")
        %p
          = t("dashboard.create_note")
        %p.small
          = t("dashboard.create_preparation_note")
        %p.small
          = link_to t('dashboard.explore_examples'), explore_path
    - elsif @pres.show_explore_button?
      %div.empty-state
        %p
          = t("dashboard.no_courses_student")
        %p
          = t("dashboard.join_note")
        %p.small
          = link_to t('dashboard.explore_course_pages'), explore_path

  - else
    - # Courses list
    - if @pres.is_admin?
      = render "courses/user_courses"
    - else
      - @pres.current.each do |course|
        = render "course_row", course: course

    - # Archived/past courses
    - if @pres.past.any?
      %h2
        = t("courses.archived")
      - @pres.past.each do |course|
        = link_to course_slug_path(course.slug), {class: 'course course-past'} do
          %span.button.border
            = t("courses.view_page")
          %h2.course-title
            = course.title
            %span.course-term= course.term