config/routes.rb
# Page titles on Wikipedia may include dots, so this constraint is needed.

Rails.application.routes.draw do
  get 'errors/file_not_found'
  get 'errors/unprocessable'
  get 'errors/login_error'
  get 'errors/internal_server_error'
  get 'errors/incorrect_passcode'

  # Sessions
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    # OmniAuth may fall back to :new_user_session when the OAuth flow fails.
    # So, we treat it as a login error.
    get 'sign_in', to: 'errors#login_error', as: :new_user_session

    get 'sign_out', to: 'users#signout', as: :destroy_user_session
    get 'sign_out_oauth', to: 'devise/sessions#destroy',
                          as: :true_destroy_user_session
  end

  # Users
  controller :users do
    get 'users/revisions' => 'users#revisions', :as => :user_revisions
  end

  resources :assignments

  # Self-enrollment: joining a course by entering a passcode or visiting a url
  get 'courses/:course_id/enroll/:passcode' => 'self_enrollment#enroll_self',
      constraints: { course_id: /.*/ }

  # Courses
  controller :courses do
    get 'courses/*id/get_wiki_top_section' => 'courses#get_wiki_top_section',
        :as => :get_wiki_top_section, constraints: { id: /.*/ }
    get 'courses/new' => 'courses#new',
        constraints: { id: /.*/ } # repeat of resources

    get 'courses/*id/manual_update' => 'courses#manual_update',
        :as => :manual_update, constraints: { id: /.*/ }
    get 'courses/*id/notify_untrained' => 'courses#notify_untrained',
        :as => :notify_untrained, constraints: { id: /.*/ }

    get 'courses/*id/check' => 'courses#check',
        :as => :check, constraints: { id: /.*/ }
    match 'courses/*id/cohort' => 'courses#list',
          constraints: { id: /.*/ }, via: [:post, :delete]
    match 'courses/*id/tag' => 'courses#tag',
          constraints: { id: /.*/ }, via: [:post, :delete]
    match 'courses/*id/user' => 'users#enroll',
          constraints: { id: /.*/ }, via: [:post, :delete]

    get 'courses/:school/:titleterm(/:endpoint(/*any))' => 'courses#show',
        defaults: { endpoint: 'overview' }, :as => 'show',
        constraints: {
          school: /[^\/]*/,
          titleterm: /[^\/]*/
        }
    post 'clone_course/:id' => 'courses#clone'
    post 'courses/:id/update_syllabus' => 'courses#update_syllabus'
  end

  get 'lookups/(:action)(.:format)' => 'lookups'

  # Assigning articles to students
  post 'courses/:course_id/users' => 'users#save_assignments',
       constraints: { course_id: /.*/ }

  # Timeline
  resources :courses, constraints: { id: /.*/ } do
    resources :weeks, only: [:index, :new, :create], constraints: { id: /.*/ }
    # get 'courses' => 'courses#index'
  end
  resources :weeks, only: [:index, :show, :edit, :update, :destroy]
  resources :blocks, only: [:show, :edit, :update, :destroy]
  resources :gradeables, collection: { update_multiple: :put }
  post 'courses/:course_id/timeline' => 'timeline#update_timeline',
       constraints: { course_id: /.*/ }

  get 'revisions' => 'revisions#index'

  resources :courses_users, only: [:index]

  # Article Finder
  if Features.enable_article_finder?
    get 'article_finder(/*any)' => 'article_finder#index'
    post 'article_finder(/*any)' => 'article_finder#results'
  end

  # Reports and analytics
  get 'analytics(/*any)' => 'analytics#index'
  post 'analytics(/*any)' => 'analytics#results'

  # Cohort data
  controller :cohorts do
    get 'cohorts/:slug/students' => 'cohorts#students'
  end

  # Recent Activity
  get 'recent-activity/plagiarism/report' => 'recent_activity#plagiarism_report'
  get 'recent-activity(/*any)' => 'recent_activity#index', as: :recent_activity

  # Revision analytics JSON API for React
  get 'revision_analytics/dyk_eligible',
      controller: 'revision_analytics',
      action: 'dyk_eligible'
  get 'revision_analytics/suspected_plagiarism',
      controller: 'revision_analytics',
      action: 'suspected_plagiarism'
  get 'revision_analytics/recent_edits',
      controller: 'revision_analytics',
      action: 'recent_edits'
  get 'revision_analytics/recent_uploads',
      controller: 'revision_analytics',
      action: 'recent_uploads'



  # Wizard
  get 'wizards' => 'wizard#wizard_index'
  get 'wizards/:wizard_id' => 'wizard#wizard'
  post 'courses/:course_id/wizard/:wizard_id' => 'wizard#submit_wizard',
       constraints: { course_id: /.*/ }

  # Training
  get 'training' => 'training#index'
  get 'training/:library_id' => 'training#show', as: :training_library
  get 'training/:library_id/:module_id' => 'training#training_module', as: :training_module
  post 'training_modules_users' => 'training_modules_users#create_or_update'

  # for React
  get 'training/:library_id/:module_id(/*any)' => 'training#slide_view'

  # API for slides for a module
  get 'training_modules' => 'training_modules#index'
  get 'training_module' => 'training_modules#show'


  # Misc
  # get 'courses' => 'courses#index'
  get 'explore' => 'explore#index'
  # get 'courses/*id' => 'courses#show', :as => :show, constraints: { id: /.*/ }

  # ask.wikiedu.org search box
  get 'ask' => 'ask#search'

  # Authenticated users root to the courses dashboard
  authenticated :user do
    root to: "dashboard#index", as: :courses_dashboard
  end

  # Unauthenticated users root to the home page
  root to: 'home#index'

  mount Rapidfire::Engine => "/surveys/rapidfire", :as => 'rapidfire'
  get '/surveys/results' => 'surveys#results_index', as: 'results'
  resources :survey_assignments, path: 'surveys/assignments'
  post '/surveys/clone/:id' => 'surveys#clone'
  put '/surveys/question_position' => 'questions#update_position'
  get '/survey/results/:id' => 'surveys#results', as: 'survey_results'
  get '/survey/question/results/:id' => 'questions#results', as: 'question_results'
  get '/surveys/question_group_question/:id' => 'questions#get_question'
  get '/surveys/:id/question_group' => 'surveys#edit_question_groups', :as => "edit_question_groups"
  post '/surveys/question_group/clone/:id' => 'surveys#clone_question_group'
  post '/surveys/question/clone/:id' => 'surveys#clone_question'
  post '/surveys/update_question_group_position' => 'surveys#update_question_group_position'
  resources :surveys
  get '/surveys/select_course/:id' => 'surveys#course_select'
  put '/survey_notification' => 'survey_notifications#update'
  post '/survey_notification/create' => 'survey_assignments#create_notifications', as: 'create_notifications'
  post '/survey_notification/send' => 'survey_assignments#send_notifications', as: 'send_notifications'

  # Onboarding
  get 'onboarding(/*any)' => 'onboarding#index', as: :onboarding
  put 'users/onboard' => 'users#onboard', as: :onboard

  # Route aliases for React frontend
  get '/course_creator(/*any)' => 'dashboard#index', as: :course_creator

  get '/feedback' => 'feedback_form_responses#new', as: :feedback
  get '/feedback_form_responses' => 'feedback_form_responses#index'
  get '/feedback_form_responses/:id' => 'feedback_form_responses#show', as: :feedback_form_response
  post '/feedback_form_responses' => 'feedback_form_responses#create'
  get '/feedback/confirmation' => 'feedback_form_responses#confirmation'

  # Errors
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/599', to: 'errors#login_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/helpers/question_group_helper.rb
module QuestionGroupHelper
  def check_conditionals(question_group)
    return true if @notification == false
    @question_group_cohorts = question_group.cohorts.pluck(:id)
    @question_group_tags = question_group.tags.split(',')
    @course = @notification.course
    course_has_tags && course_in_cohorts
  end

  def course_has_tags
    return true if @question_group_tags.empty?
    course_tags = @course.tags.pluck(:tag)
    matching = course_tags.select do |t|
      @question_group_tags.include?(t)
    end
    matching.length == @question_group_tags.length
  end

  def course_in_cohorts
    return true if @question_group_cohorts.empty?
    matching = @question_group_cohorts.select do |cohort_id|
      CohortsCourses.where(course_id: @course.id, cohort_id: cohort_id).count > 0
    end
    matching.count == @question_group_cohorts.count
  end
end

app/helpers/question_groups_helper.rb
module QuestionGroupsHelper
  def check_conditionals(question_group)
    return true if @course.nil?
    @question_group_cohorts = question_group.cohorts.pluck(:id)
    @question_group_tags = question_group.tags.nil? ? [] : question_group.tags.split(',')
    course_has_tags && course_in_cohorts
  end

  def course_has_tags
    return true if @question_group_tags.empty?
    course_tags = @course.tags.pluck(:tag)
    matching = course_tags.select do |t|
      @question_group_tags.include?(t)
    end
    matching.length == @question_group_tags.length
  end

  def course_in_cohorts
    return true if @question_group_cohorts.empty?
    matching = @question_group_cohorts.select do |cohort_id|
      CohortsCourses.where(course_id: @course.id, cohort_id: cohort_id).count > 0
    end
    matching.count == @question_group_cohorts.count
  end
end

app/views/rapidfire/question_groups/_admin_header.html.haml
.section-header.surveys__admin-header.surveys__admin-header--question-groups
  .container
    %div
      %h1 Question Groups
    .surveys__admin-header__action
      - if params.key?(:cancellable)
        = link_to "Cancel", @question_group, method: :delete, :class => 'button button--no-margin border', :data => {confirm: "Are you sure you want to delete this Question Group?"}
      - else
        = link_to "New Question Group", new_question_group_path, :class => 'button button--no-margin border'

app/views/rapidfire/question_groups/_admin_header_edit.html.haml
.section-header.surveys__admin-header.surveys__admin-header--question-groups.surveys__admin-header--question-groups--edit
  .container
    %div
      %h1 Editing #{@question_group.name}
    .surveys__admin-header__action
      .form__actions
        = f.button :submit,"Save Question Group", class: 'button border button--no-margin'

app/views/rapidfire/question_groups/_question_group.html.haml
%li.survey__admin-row.survey__admin-row--question-group{:id => "question_group_#{question_group.id}"}
  .survey__admin-row__title
    %strong.name= question_group.name
  .survey__admin-row__col
    .contextual Status
    %strong.question-group-color.status= question_group_status(question_group)
  .survey__admin-row__col
    .contextual Questions
    %strong= question_group.questions.count
  .survey__admin-row__col
    .contextual Last Author
    %span.author= survey_author(question_group)
  -# .survey__admin-row__col
  -#   .contextual Created
  -#   %span= question_group.created_at.strftime("%B %d, %Y")
  .survey__admin-row__col
    .contextual Updated
    %span= question_group.updated_at.strftime("%B %d, %Y")
  .survey__admin-row__col.survey__admin-row__col--actions
    .course-list__col
      = link_to "Edit", edit_question_group_path(question_group)
    .course-list__col
      = link_to "Clone", "/surveys/question_group/clone/#{question_group.id}", method: :post
    -# .course-list__col
    -#   = link_to "Add Question", new_question_group_question_path(question_group)
    - if question_group.questions.length > 0
      .course-list__col
        = link_to "Preview", "#{new_question_group_answer_group_path(question_group)}?preview"
    .course-list__col
      = link_to "Results", [:results, question_group]
    -# .course-list__col
    -#   = link_to "Delete", [question_group], method: :delete, :data => {confirm: "Are you sure you want to delete #{question_group.name} survey?"}

app/views/rapidfire/question_groups/edit.html.haml
- @questions = @question_group.questions
= simple_form_for(@question_group) do |f|
  = f.error_notification
  .section-header.surveys__admin-header.surveys__admin-header--question-groups.surveys__admin-header--question-groups--edit
    .container
      %div
        %h1 Editing #{@question_group.name}
      .surveys__admin-header__action
        .form__actions
          = f.button :submit, class: 'button button--no-margin border'

  .container.survey__admin
    .form__block.form__block--equal-height
      .block.form__settings
        .form__settings__tabs
          .tab
            %h3 Settings
        = f.input :name, label: "Question Group Name", class: 'input--large'
        .form__row
          = f.association :cohorts, label_method: :title, input_html: { data: { chosen_select: true }}
        .form__row
          %label Tags
          = select_tag "question_group[tags]", options_for_select(@available_tags, @question_group_tags), multiple: true, data: { chosen_select: true }
        .form__actions.danger
          = link_to "Delete Question Group", @question_group, method: :delete, :data => {confirm: "Are you sure you want to delete #{@question_group.name}?"}

      .form__question-list
        = render 'rapidfire/questions/question_group_list'

app/views/rapidfire/question_groups/index.html.haml
= render 'admin_header'
.container.survey__edit
  - if @question_groups.length > 0
    #searchable-list
      .list-search__form
        %input.fuzzy-search{placeholder: 'Search Question Groups'}
      %ul.list.survey__admin__row-container= render partial: "question_group", collection: @question_groups
  - else
    %p.light-text
      No Question Groups. #{link_to "Create One", new_question_group_path}

app/views/rapidfire/question_groups/new.html.haml
-# = render partial: 'admin_header'
- @questions = @question_group.questions
= simple_form_for(@question_group) do |f|
  = f.error_notification
  .section-header.surveys__admin-header.surveys__admin-header--question-groups.surveys__admin-header--question-groups--edit
    .container
      %div
        %h1 New Question Group
      .surveys__admin-header__action
        .form__actions
          = f.button :submit, "Save Question Group", class: 'button button--no-margin border'

  .container.survey__admin
    .form__block.form__block--equal-height
      .block.form__settings
        .form__settings__tabs
          .tab
            %h3 Settings
        = f.input :name, label: "Question Group Name", input_html: { class: "input--large", required: true }
        .form__row
          = f.association :cohorts, label_method: :title, input_html: { data: { chosen_select: true }}
        .form__row
          %label Tags
          = select_tag "question_group[tags]", options_for_select(@available_tags, @question_group_tags), multiple: true, data: { chosen_select: true }
      .form__question-list
        .survey__questions-list.clearfix
          .survey__admin-actions.clearfix
            %h3 Questions
            = f.button :submit, "Add Question", class: 'button dark', name: "redirect_to_edit"

app/views/rapidfire/question_groups/results.html.erb
<%= render 'admin_header' %>
<div class='container'>
<div class='section-header'>
  <h1>Results for <%= @question_group.name %></h1>
</div>

<% if @question_group_results.length > 0 %>
<%- @question_group_results.each do |result| %>
  <div class='block'>
    <h4><%= result.question.question_text %></h4>

      <%- if result.results.is_a?(Array) %>
        <ol>
          <%- result.results.each do |answer| %>
            <li><%= answer %></li>
          <% end %>
        </ol>
      <% elsif result.results.is_a?(Hash) %>
        <table>
          <thead>
            <tr>
              <th><strong>Option</strong></th>
              <th><strong>Count</strong></th>
              <th><strong>Follow Up Question: <%= result.question.follow_up_question_text %></strong></th>
            </tr>
          </thead>
          <tbody>
            <%- result.results.each_with_index do |opt, index| %>
              <tr>
                <td><strong><%= opt[0] %></strong></td>
                <td><strong><%= opt[1] %></strong></td>
                <td><%= result.follow_up_results[index] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
  </div>
<% end %>
<% else %>
<div class='block'>no results collected</div>
<% end %>

</div>