config/routes.rb
# Page titles on Wikipedia may include dots, so this constraint is needed.

Rails.application.routes.draw do
  get 'errors/file_not_found'
  get 'errors/unprocessable'
  get 'errors/login_error'
  get 'errors/internal_server_error'
  get 'errors/incorrect_passcode'

  # Sessions
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    # OmniAuth may fall back to :new_user_session when the OAuth flow fails.
    # So, we treat it as a login error.
    get 'sign_in', to: 'errors#login_error', as: :new_user_session

    get 'sign_out', to: 'users#signout', as: :destroy_user_session
    get 'sign_out_oauth', to: 'devise/sessions#destroy',
                          as: :true_destroy_user_session
  end

  # Users
  controller :users do
    get 'users/revisions' => 'users#revisions', :as => :user_revisions
  end

  resources :assignments

  # Self-enrollment: joining a course by entering a passcode or visiting a url
  get 'courses/:course_id/enroll/:passcode' => 'self_enrollment#enroll_self',
      constraints: { course_id: /.*/ }

  # Courses
  controller :courses do
    get 'courses/*id/get_wiki_top_section' => 'courses#get_wiki_top_section',
        :as => :get_wiki_top_section, constraints: { id: /.*/ }
    get 'courses/new' => 'courses#new',
        constraints: { id: /.*/ } # repeat of resources

    get 'courses/*id/manual_update' => 'courses#manual_update',
        :as => :manual_update, constraints: { id: /.*/ }
    get 'courses/*id/notify_untrained' => 'courses#notify_untrained',
        :as => :notify_untrained, constraints: { id: /.*/ }

    get 'courses/*id/check' => 'courses#check',
        :as => :check, constraints: { id: /.*/ }
    match 'courses/*id/cohort' => 'courses#list',
          constraints: { id: /.*/ }, via: [:post, :delete]
    match 'courses/*id/tag' => 'courses#tag',
          constraints: { id: /.*/ }, via: [:post, :delete]
    match 'courses/*id/user' => 'users#enroll',
          constraints: { id: /.*/ }, via: [:post, :delete]

    get 'courses/:school/:titleterm(/:endpoint(/*any))' => 'courses#show',
        defaults: { endpoint: 'overview' }, :as => 'show',
        constraints: {
          school: /[^\/]*/,
          titleterm: /[^\/]*/
        }
    post 'clone_course/:id' => 'courses#clone'
    post 'courses/:id/update_syllabus' => 'courses#update_syllabus'
  end

  get 'lookups/(:action)(.:format)' => 'lookups'

  # Assigning articles to students
  post 'courses/:course_id/users' => 'users#save_assignments',
       constraints: { course_id: /.*/ }

  # Timeline
  resources :courses, constraints: { id: /.*/ } do
    resources :weeks, only: [:index, :new, :create], constraints: { id: /.*/ }
    # get 'courses' => 'courses#index'
  end
  resources :weeks, only: [:index, :show, :edit, :update, :destroy]
  resources :blocks, only: [:show, :edit, :update, :destroy]
  resources :gradeables, collection: { update_multiple: :put }
  post 'courses/:course_id/timeline' => 'timeline#update_timeline',
       constraints: { course_id: /.*/ }

  get 'revisions' => 'revisions#index'

  resources :courses_users, only: [:index]

  # Article Finder
  if Features.enable_article_finder?
    get 'article_finder(/*any)' => 'article_finder#index'
    post 'article_finder(/*any)' => 'article_finder#results'
  end

  # Reports and analytics
  get 'analytics(/*any)' => 'analytics#index'
  post 'analytics(/*any)' => 'analytics#results'

  # Cohort data
  controller :cohorts do
    get 'cohorts/:slug/students' => 'cohorts#students'
  end

  # Recent Activity
  get 'recent-activity/plagiarism/report' => 'recent_activity#plagiarism_report'
  get 'recent-activity(/*any)' => 'recent_activity#index', as: :recent_activity

  # Revision analytics JSON API for React
  get 'revision_analytics/dyk_eligible',
      controller: 'revision_analytics',
      action: 'dyk_eligible'
  get 'revision_analytics/suspected_plagiarism',
      controller: 'revision_analytics',
      action: 'suspected_plagiarism'
  get 'revision_analytics/recent_edits',
      controller: 'revision_analytics',
      action: 'recent_edits'
  get 'revision_analytics/recent_uploads',
      controller: 'revision_analytics',
      action: 'recent_uploads'



  # Wizard
  get 'wizards' => 'wizard#wizard_index'
  get 'wizards/:wizard_id' => 'wizard#wizard'
  post 'courses/:course_id/wizard/:wizard_id' => 'wizard#submit_wizard',
       constraints: { course_id: /.*/ }

  # Training
  get 'training' => 'training#index'
  get 'training/:library_id' => 'training#show', as: :training_library
  get 'training/:library_id/:module_id' => 'training#training_module', as: :training_module
  post 'training_modules_users' => 'training_modules_users#create_or_update'

  # for React
  get 'training/:library_id/:module_id(/*any)' => 'training#slide_view'

  # API for slides for a module
  get 'training_modules' => 'training_modules#index'
  get 'training_module' => 'training_modules#show'


  # Misc
  # get 'courses' => 'courses#index'
  get 'explore' => 'explore#index'
  # get 'courses/*id' => 'courses#show', :as => :show, constraints: { id: /.*/ }

  # ask.wikiedu.org search box
  get 'ask' => 'ask#search'

  # Authenticated users root to the courses dashboard
  authenticated :user do
    root to: "dashboard#index", as: :courses_dashboard
  end

  # Unauthenticated users root to the home page
  root to: 'home#index'

  mount Rapidfire::Engine => "/surveys/rapidfire", :as => 'rapidfire'
  get '/surveys/results' => 'surveys#results_index', as: 'results'
  resources :survey_assignments, path: 'surveys/assignments'
  post '/surveys/clone/:id' => 'surveys#clone'
  put '/surveys/question_position' => 'questions#update_position'
  get '/survey/results/:id' => 'surveys#results', as: 'survey_results'
  get '/survey/question/results/:id' => 'questions#results', as: 'question_results'
  get '/surveys/question_group_question/:id' => 'questions#get_question'
  get '/surveys/:id/question_group' => 'surveys#edit_question_groups', :as => "edit_question_groups"
  post '/surveys/question_group/clone/:id' => 'surveys#clone_question_group'
  post '/surveys/question/clone/:id' => 'surveys#clone_question'
  post '/surveys/update_question_group_position' => 'surveys#update_question_group_position'
  resources :surveys
  get '/surveys/select_course/:id' => 'surveys#course_select'
  put '/survey_notification' => 'survey_notifications#update'
  post '/survey_notification/create' => 'survey_assignments#create_notifications', as: 'create_notifications'
  post '/survey_notification/send' => 'survey_assignments#send_notifications', as: 'send_notifications'

  # Onboarding
  get 'onboarding(/*any)' => 'onboarding#index', as: :onboarding
  put 'users/onboard' => 'users#onboard', as: :onboard

  # Route aliases for React frontend
  get '/course_creator(/*any)' => 'dashboard#index', as: :course_creator

  get '/feedback' => 'feedback_form_responses#new', as: :feedback
  get '/feedback_form_responses' => 'feedback_form_responses#index'
  get '/feedback_form_responses/:id' => 'feedback_form_responses#show', as: :feedback_form_response
  post '/feedback_form_responses' => 'feedback_form_responses#create'
  get '/feedback/confirmation' => 'feedback_form_responses#confirmation'

  # Errors
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/599', to: 'errors#login_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/survey.rb
require 'csv'

class Survey < ActiveRecord::Base
  has_paper_trail
  has_many :survey_assignments, dependent: :destroy
  has_and_belongs_to_many :rapidfire_question_groups,
                          class_name: 'Rapidfire::QuestionGroup',
                          join_table: 'surveys_question_groups',
                          association_foreign_key: 'rapidfire_question_group_id'
  accepts_nested_attributes_for :rapidfire_question_groups

  def status
    active = survey_assignments.map(&:active?)
    return "In Use (#{active.count})" unless active.empty?
    '--'
  end

  def to_csv
    CSV.generate do |csv|
      csv << ['Question Group',
              'Grouped Question',
              'Question Id',
              'Question',
              'Answer',
              'Follow Up Question',
              'Follow Up Answer',
              'User',
              'User Role',
              'Course Slug',
              'Course Cohorts',
              'Course Tags']
      rapidfire_question_groups.each do |question_group|
        question_group.questions.each do |question|
          question.answers.each do |answer|
            course = answer.course(id)
            course_slug = course.nil? ? nil : course.slug
            cohorts = course.nil? ? nil : course.cohorts.collect(&:title).join(', ')
            tags = course.nil? ? nil : course.tags.collect(&:tag).join(', ')
            csv << [
              question_group.name,
              question.validation_rules[:grouped_question],
              question.id,
              question.question_text,
              answer.answer_text,
              question.follow_up_question_text,
              answer.follow_up_answer_text,
              answer.user.username,
              answer.courses_user_role(id),
              course_slug,
              cohorts,
              tags
            ]
          end
        end
      end
    end
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
  include CourseHelper

  def survey_course_title
    if @course.nil?
      'Survey'
    else
      "Survey for #{@course.title} (#{@course.term})"
    end
  end

  def render_answer_form_helper(answer, form)
    partial = question_type(answer)
    render partial: "rapidfire/answers/#{partial}",
           locals: { f: form, answer: answer, course: @course }
  end

  def render_matrix_answer_labels(answer)
    render partial: 'rapidfire/answers/matrix_answer_labels',
           locals: { answer: answer, course: @course }
  end

  def survey_preview_url(survey)
    "#{survey_url(survey)}?preview"
  end

  def question_answer_field_name(form, multiple)
    name = "answer_group[#{form.object.question_id}][answer_text]"
    if multiple
      name + '[]'
    else
      name
    end
  end

  def survey_select(f, answer, course)
    multiple = answer.question.multiple
    field_name = question_answer_field_name(f, multiple)
    options = answer_options(answer, course).collect { |o| o.is_a?(Array) ? [o[1].tr('_', ' ').to_s, o[0]] : o }
    if options.empty?
      content_tag :div, 'remove me', data: { remove_me: true }
    else
      select_tag(field_name, options_for_select(options),
                 include_blank: answer.question.multiple ? 'Select all that apply' : 'Select an option',
                 required: is_required_question?(answer),
                 multiple: answer.question.multiple)
    end
  end

  def answer_options(answer, course)
    question = answer.question
    if !question.options.empty?
      question.options.collect { |q| [strip_tags(q), q, q] }
    elsif !course.nil?
      course_answer_options(question.course_data_type, course)
    end
  end

  def course_answer_options(type, course)
    case type
    when 'Students'
      students = course.users.role('student')
      students.collect { |s| [s.id, s.username, contribution_link(s).to_s] }
    when 'Articles'
      course.articles.collect { |a| [a.id, a.title, "<a href='#{article_url(a)}' target='_blank'>#{a.title}</a>"] }
    when 'WikiEdu Staff'
      staff = course.users.role('wiki_ed_staff')
      staff.collect { |s| [s.id, s.username, contribution_link(s).to_s] }
    end
  end

  def can_administer?
    current_user && current_user.admin?
  end

  def question_type(answer)
    question_type_to_string(answer.question)
  end

  def question_type_to_string(question)
    question.type.to_s.split('::').last.downcase
  end

  def is_required_question?(answer)
    answer.question.validation_rules[:presence].to_i == 1
  end

  def is_grouped_question(answer)
    if answer.nil? || answer.question.nil?
      false
    else
      answer.question.validation_rules[:grouped].to_i == 1
    end
  end

  def grouped_question(answer)
    answer.question.validation_rules[:grouped_question]
  end

  def has_follow_up_question(answer)
    answer.question.follow_up_question_text? && !answer.question.follow_up_question_text.empty?
  end

  def start_of_group(options = {})
    answers = options[:answers]
    index = options[:index]
    answer = answers[index]
    return false unless is_grouped_question(answer)
    return true if index == 0

    previous_answer = answers[index - 1]
    return true unless is_grouped_question(previous_answer)
    return true unless questions_in_same_group?(answer, previous_answer)
    return false
  end

  def end_of_group(answer, answer_group_builder, index)
    return false unless is_grouped_question(answer)

    total_questions = answer_group_builder.answers.length
    is_last_question = (index + 1 == total_questions)
    return true if is_last_question

    next_question = answer_group_builder.answers[index + 1]
    return true unless questions_in_same_group?(answer, next_question)

    return false
  end

  def question_group_locals(surveys_question_group, index, total, results = false)
    @question_group = surveys_question_group.rapidfire_question_group
    @answer_group_builder = Rapidfire::AnswerGroupBuilder.new(params: {},
                                                              user: current_user,
                                                              question_group: @question_group)
    return {
      question_group: @question_group,
      answer_group_builder: @answer_group_builder,
      question_group_index: index,
      surveys_question_group: surveys_question_group,
      total: total,
      results: results
    }
  end

  def question_conditional_string(question)
    return '' if question.nil?
    return question.conditionals
  end

  def has_course_data(question_form)
    !question_form.course_data_type.nil? && !question_form.course_data_type.empty?
  end

  def question_form_has_follow_up_question(question_form)
    !question_form.follow_up_question_text.nil? && !question_form.follow_up_question_text.empty?
  end

  def conditional_string(answer)
    if answer.question.conditionals?
      string = strip_tags(answer.question.conditionals).tr(' ', '_').tr("'", "\\'")
      "data-conditional-question=#{string}"
    end
  end

  def is_radio_type(answer)
    question_type(answer) == 'radio'
  end

  private

  def set_course
    @course = find_course_by_slug(params[:course_slug]) if course_slug?
  end

  def set_course_for_survey
    set_course
    return unless survey_has_course_questions? && !course_slug?
    @courses = Course.all
    render 'course_select'
  end

  def set_course_for_question_group
    set_course
    return unless course_questions?(@question_group) && !course_slug?
    @courses = Course.all
    render 'course_select'
  end

  def survey_notification_id(notification)
    return nil if notification == false || notification.nil?
    return notification.id
  end

  def survey_class_for_path(req, path)
    current_path_segments = req.path.split('/').reject(&:blank?)
    active_path = path.split('/').reject(&:blank?).last
    current_path_segments.last == active_path ? 'active' : nil
  end

  ######################################
  # Methods called only from this file #
  ######################################

  def course_slug?
    params.key?('course_slug')
  end

  def course_questions?(question_group)
    !question_group.questions.course_data_questions.empty?
  end

  def questions_in_same_group?(first, second)
    return false if first.nil? || second.nil?
    grouped_question(first) == grouped_question(second)
  end

  def survey_has_course_questions?
    @surveys_question_groups.each do |sqg|
      return true if course_questions?(sqg.question_group)
    end
    false
  end
end

app/views/surveys/_form.html.haml
= simple_form_for(@survey) do |f|
  = f.error_notification
  = render partial: 'surveys/admin_header_edit', locals: { f: f }
  .container.survey__admin
    .form__block.form__block--equal-height
      .block.form__settings
        .form__settings__tabs
          .tab
            %h3 Settings
        .form-inputs.light-text.survey__title-input
          = f.input :name

        .form-inputs.light-text.survey__title-input
          = f.input :open, label: "Survey Open (Anyone may take it)"
          = f.input :closed, label: "Close Survey"
        .form__actions.danger
          = link_to 'Delete this survey', @survey, :method => :delete, :data => { :confirm => 'Are you sure?' }

      .form__question-group-list
        .light-text
          %h3 Survey Question Groups
          %div.py= link_to "Edit Question Groups", edit_question_groups_path(@survey.id)

        - if @surveys_question_groups.length
          %ul.list.list--survey{'data-sortable-question-groups' => @survey.id}
            - @surveys_question_groups.each do |group|
              - question_group = group.rapidfire_question_group
              %li.question-group-row.row.course-list__row.row--survey-question{'data-item-id' => question_group.id}
                .row__wrapper
                  .course-list__row__title
                    %strong= question_group.name
                  %div= link_to "Edit", rapidfire.question_group_questions_path(question_group)
            - if @surveys_question_groups.length > 1
              %li.survey__admin-tools
                %span Drag to reorder questions. (Changes will be saved automatically.)

        %div.light-text
          = f.label :intro, "Survey Introduction"
          = f.hidden_field :intro , id: 'intro', value: @survey.intro
          %trix-editor{'input' => "intro"}

        %div.light-text
          = f.label :thanks, "Survey Thank You"
          = f.hidden_field :thanks , id: 'thanks', value: @survey.thanks
          %trix-editor{'input' => "thanks"}

        .form__actions
          = f.button :submit, :class => 'button dark'
          = link_to "Preview Survey", survey_preview_url(@survey), :class => 'button'

app/views/surveys/_loading.html.haml
.spinner
  .bounce1
  .bounce2
  .bounce3

app/views/surveys/_navigation.html.haml
- if can_administer?
  .survey__admin__nav
    %ul.container
      %li= link_to 'Question Groups', rapidfire.question_groups_path, class: survey_class_for_path(request, rapidfire.question_groups_path)
      %li= link_to 'Surveys', surveys_path, class: survey_class_for_path(request, surveys_path)
      %li= link_to 'Assignment', survey_assignments_path, class: survey_class_for_path(request, survey_assignments_path)
      %li= link_to 'Results', results_path, class: survey_class_for_path(request, results_path)

app/views/surveys/_question_group.html.erb
<!-- rapidfire/question_groups/2/answer_groups/new -->
<%= form_for(Rapidfire::AnswerGroup.new,
    :url => rapidfire.question_group_answer_groups_path(question_group),
    :html => {'data-survey-form' => true, 'data-question-group' => question_group_index, tabindex: -1 }) do |f| %>

  <div <% if !results %>data-question-group-blocks="<%= question_group_index %>"<% end %>>
    <%- @answer_group_builder.answers.each_with_index do |answer, index| %>

    <% next if results && question_type(answer) == 'text' %>

    <% is_start_of_group = start_of_group(answers:@answer_group_builder.answers, index: index) %>
    <% is_end_of_group = end_of_group(answer, @answer_group_builder, index) %>

    <% if is_start_of_group %>
      <div class='block__container' data-block-index='<%= index %>' data-survey-index='<%= %>'>
        <div class="block not-seen disabled survey__question--matrix <%= question_type(answer) %>">
    <% end %>

      <%= f.fields_for("#{answer.question.id}", answer) do |answer_form| %>

      <%= render partial: "rapidfire/answers/matrix_question_text", locals: {f: f, answer: answer, name: question_group.name} %>

      <% if !is_grouped_question(answer) %>
        <div class='block__container'><div id="question_<%= answer.question.id %>" class='block disabled not-seen question-type--<%= question_type(answer) %> <% if answer.errors.any? %>block--errors<% end %> <% if is_required_question?(answer) %>required<% end %>' data-survey-block='<%= index + 1 %>'>
      <% end %>

          <% if !results && is_grouped_question(answer) && is_start_of_group && is_radio_type(answer) %>
            <div class='survey__question-row first matrix-row' data-block-index='<%= index %>'>
              <%= render_matrix_answer_labels(answer) %>
            </div>
          <% end %>

          <div <% if is_grouped_question(answer) %>id="question_<%= answer.question.id %>"<% end %> data-question-group="<%= question_group_index %>" class='survey__question-row <%= is_grouped_question(answer) ? 'matrix-row' : '' %> <%= index.even? ? '' : 'odd' %>  <%= is_end_of_group ? "last" : "" %> <% if is_required_question?(answer) %>required<% end %>' <%= conditional_string(answer) %>>
            <% if results %>
              <%= render partial: "rapidfire/answers/question_text", locals: {f: answer_form, answer: answer} %>
              <%= render partial: "question_results", locals: { question: answer.question } %>
            <% else %>
              <%= render_answer_form_helper(answer, answer_form) %>
            <% end %>
          </div>


          <% if !is_grouped_question(answer) || is_end_of_group  || is_grouped_question(answer) && !is_grouped_question(@answer_group_builder.answers[index + 1]) %>
            <% if has_follow_up_question(answer) && !results %>
              <%= render partial: "rapidfire/answers/follow_up_question", locals: {f: answer_form, answer: answer } %>
            <% end %>

            <% if !results %>
            <div class='survey__block-nav'>
              <button tabindex="-1" class='button survey__prev border' data-prev-survey-block>Previous</button>
              <div class='survey__block-nav__next-container'>
                  <div data-errors></div>
                <% if question_group_index + 1 == total && @answer_group_builder.answers.length == index + 1 %>
                  <button tabindex="-1" class='button dark' data-next-survey-block data-submit-survey data-no-validate>Submit Survey<span class='icon icon-rt_arrow'></span></button>
                <% else %>
                  <button tabindex="-1" class='button survey__next dark' data-next-survey-block>Next <span class='icon icon-rt_arrow'></span></button>
                <% end %>
              </div>
            </div>
            <% end %>
          <% end %>
        <% if !is_grouped_question(answer) %>
        </div></div>
        <% end %>
      <% end %><!-- End of  fields_for -->

    <% if is_end_of_group %></div></div><% end %>

    <% end %><!-- End of  @answer_group_builder.answers.each_with_index -->

  </div>



<% end %>

app/views/surveys/_question_results.html.haml
%div{data: { question_results: question_results_data(question) }}
.results__question-footer
  %strong= respondents(question)
  = link_to "Download Results CSV", question_results_path(question, format: 'csv')

app/views/surveys/_results_admin_header.html.haml
.section-header.surveys__admin-header.surveys__admin-header--survey_results
  .container
    %div
      %h1 Results
    .surveys__admin-header__action
      -#

app/views/surveys/_survey.html.haml
%li.survey__admin-row.survey__admin-row--survey
  .survey__admin-row__title
    %strong.name= survey.name
  .survey__admin-row__col
    .contextual Status
    %strong.survey-color.status= survey_status(survey)
  .survey__admin-row__col
    .contextual Groups | Questions
    %strong= survey_question_stats(survey)
  .survey__admin-row__col
    .contextual Last Author
    %span.author= survey_author(survey)
  -# .survey__admin-row__col
  -#   .contextual Created
  -#   %span= survey.created_at.strftime("%B %d, %Y")
  .survey__admin-row__col
    .contextual Updated
    %span= survey.updated_at.strftime("%B %d, %Y")
  .survey__admin-row__col.survey__admin-row__col--actions
    = link_to 'Edit', edit_survey_path(survey)
    = link_to "Clone Survey", "/surveys/clone/#{survey.id}", method: :post
    - if survey.rapidfire_question_groups.length > 0
      = link_to 'Preview', "#{survey_url(survey)}?preview"
    = link_to 'Results', survey_results_path(survey)
    -# .course-list__col
    -#   = link_to 'Delete', survey, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/surveys/add_question_group.html.haml
.block.block--clear

  %h3 Editing Question Groups for "#{@survey.name}" Survey

  = simple_form_for(@survey) do |f|
    = f.error_notification

    .form-input
      = f.association :rapidfire_question_groups,   as: :check_boxes
  
    .form-actions
      = f.button :submit, "Update Question Groups", :class => 'button dark'

app/views/surveys/course_select.html.haml
.block.block--text.disabled.not-seen{"data-survey-block" => "0", "data-intro" => true}
  %h1.survey__title= @survey.name
  %p Select a Course for Survey
  = form_tag survey_path(@survey), method: "get" do
    - if params.has_key?(:preview)
      = check_box_tag "preview", true, true, class: 'hidden'
    = select_tag "course_slug", options_from_collection_for_select(@courses, 'slug', 'title'), required: true, include_blank: true, survey_course_select: true, placeholder: "Select your course"
    .survey__block-nav
      = submit_tag "Start Survey", class: 'button dark pull-right'

app/views/surveys/edit_question_groups.html.haml
= render 'admin_header'
.block.block--clear

  %h3 Editing Question Groups for "#{@survey.name}" Survey

  = simple_form_for(@survey) do |f|
    = f.error_notification

    .form-input
      = f.association :rapidfire_question_groups,   as: :check_boxes

    .form-actions
      = f.button :submit, "Update Question Groups", :class => 'button dark'

app/views/surveys/index.html.haml
= render 'admin_header'
.container.survey__edit
  - if @surveys.length > 0
    #searchable-list
      .list-search__form
        %input.fuzzy-search{placeholder: 'Search Surveys'}
      %ul.list= render partial: "survey", collection: @surveys
  - else
    %p.light-text
      No Surveys. #{link_to "Create One", new_survey_path}

app/views/surveys/login.html.haml
.block.text-center.survey__login
  %h1= @survey.name
  %p.lead= t('survey.login_message')
  = link_to user_omniauth_authorize_path(:mediawiki), class: 'button dark' do
    %i.icon.icon-wiki-logo
    %span= t('application.log_in')
    %span= t('application.sign_up_log_in_extended')

app/views/surveys/new.html.haml
= render 'admin_header'
.container.survey__admin
  .block.block--clear
    = simple_form_for(@survey) do |f|
      = f.error_notification

      .form-inputs.survey__title-input
        = f.input :name

        .form__row
          = f.button :submit, :class => 'button dark'

app/views/surveys/show.html.haml
- if params.key?("preview")
  .survey-previewing Preview Mode

%p#notice= notice

%div{data: {survey_form_container: true, notification: survey_notification_id(@notification)}, class: 'loading'}
  - if @survey.intro?
    .block__container
      .block.block--text.disabled.not-seen{"data-survey-block" => "0", "data-intro" => true}
        %h1.survey__title= @survey.name
        - if @survey.intro?
          = @survey.intro.html_safe
          .survey__block-nav
            %div
            %button.button.survey__next.dark{"data-next-survey-block" => "", "data-no-validate" => true}
              %span Start
              %span.icon.icon-rt_arrow


  - @surveys_question_groups.each_with_index do |group, index|
    - if check_conditionals(group.question_group) && !group.question_group.questions.empty?
      = render partial: "question_group", locals: question_group_locals(group, index, @surveys_question_groups.length)

  .block__container
    .block.block--text.block--clear.block--thank-you.disabled.not-seen{data: {thank_you: true}}
      .block--thank-you__container
        %h2.big-title Thank You!
        - if @survey.thanks?
          = @survey.thanks.html_safe